name: Code Review with OpenAI
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: nianxiongdi/ai-codereviewer@ai
        with:
          GITHUB_TOKEN:  ${{ secrets.TOKEN }}
          OPENAI_API_KEY: "sk-kfGlYjjvwM9PAI6Us5HulzXdtOXPChgo1X2qm257RlP80YZG"
          OPENAI_API_MODEL: "gpt-3.5-turbo"
          exclude: "yarn.lock,dist/**"
